{
  "url": "https://api.github.com/repos/DataDog/dd-trace-py/releases/230520647",
  "assets_url": "https://api.github.com/repos/DataDog/dd-trace-py/releases/230520647/assets",
  "upload_url": "https://uploads.github.com/repos/DataDog/dd-trace-py/releases/230520647/assets{?name,label}",
  "html_url": "https://github.com/DataDog/dd-trace-py/releases/tag/v3.10.1",
  "id": 230520647,
  "author": {
    "login": "vitor-de-araujo",
    "id": 176389253,
    "node_id": "U_kgDOCoN8hQ",
    "avatar_url": "https://avatars.githubusercontent.com/u/176389253?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/vitor-de-araujo",
    "html_url": "https://github.com/vitor-de-araujo",
    "followers_url": "https://api.github.com/users/vitor-de-araujo/followers",
    "following_url": "https://api.github.com/users/vitor-de-araujo/following{/other_user}",
    "gists_url": "https://api.github.com/users/vitor-de-araujo/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/vitor-de-araujo/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/vitor-de-araujo/subscriptions",
    "organizations_url": "https://api.github.com/users/vitor-de-araujo/orgs",
    "repos_url": "https://api.github.com/users/vitor-de-araujo/repos",
    "events_url": "https://api.github.com/users/vitor-de-araujo/events{/privacy}",
    "received_events_url": "https://api.github.com/users/vitor-de-araujo/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false
  },
  "node_id": "RE_kwDOA6uE5s4NvXdH",
  "tag_name": "v3.10.1",
  "target_commitish": "3.10",
  "name": "3.10.1",
  "draft": false,
  "immutable": false,
  "prerelease": false,
  "created_at": "2025-07-07T14:47:45Z",
  "published_at": "2025-07-07T15:43:33Z",
  "assets": [

  ],
  "tarball_url": "https://api.github.com/repos/DataDog/dd-trace-py/tarball/v3.10.1",
  "zipball_url": "https://api.github.com/repos/DataDog/dd-trace-py/zipball/v3.10.1",
  "body": "### Bug Fixes\r\n\r\n  - CI Visibility:\r\n    - This fix resolves an issue where using Test Optimization together with external retry plugins such as `flaky` or `pytest-rerunfailures` would cause the test results not to be reported correctly to Datadog. With this change, those plugins can be used with ddtrace, and test results will be reported to Datadog, but Test Optimization advanced features such as Early Flake Detection and Auto Test Retries will not be available when such plugins are used.\r\n    - This fix resolves an issue where test retry numbers were not reported correctly when tests were run with `pytest-xdist`.\r\n  - LLM Observability:\r\n    - Fixes an issue where LangGraph span links for execution flows were broken for `langgraph>=0.3.22`.\r\n"
}
